sudo: required

dist: trusty

language: node_js

node_js:
- '6.9.4'

branches:
  only:
    - develop

before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm install

script:
  - npm run test
  - npm run build

notifications:
  email: false
